export type ComponentKind = 'source' | 'bundle' | 'server';
type ComponentRecord = {
  id: string; name: string; kind: ComponentKind; target: string; purpose: string;
  artifact: string; prerequisite: string; verify: string; command?: string;
};

export const patchCatalog: ComponentRecord[] = [
  { id: 'plugin-v21-import', name: 'API 2.1 插件导入兼容', kind: 'source', target: '官方 v2026.8.250 源码', purpose: '恢复新版 RisuAI 对 API 2.1 插件的导入和更新入口，供现有桥接插件使用。', artifact: 'patches/risuai/scripts/patch-plugin-v21-import.mjs', prerequisite: '仅用于目标源码的 src/ts/plugins/plugins.svelte.ts；先运行预检，再构建。旧版 2026.8.160 已有该路径。', verify: '重新构建 RisuAI，并在浏览器实际导入、启用和触发插件。', command: 'node patches/risuai/install.mjs --patch plugin-v21-import --target <plugins.svelte.ts>' },
  { id: 'preset-switch', name: '预设切换保护', kind: 'bundle', target: '已核对的 2026.8.160 构建', purpose: '当前预设索引失效时避免切换崩溃；有效目标仍照常切换。', artifact: 'patches/risuai/scripts/patch-preset-switch.mjs', prerequisite: '脚本匹配特定构建锚点，更新 RisuAI 后必须重新核对。替换前备份目标资源。', verify: '预检及安装器均检查语法；回读目标文件哈希后，在浏览器测试切换及保存。', command: 'node patches/risuai/install.mjs --patch preset-switch --frontend <database.js>' },
  { id: 'api-profiles', name: '自定义 API 配置档与模型列表', kind: 'bundle', target: '自定义模型设置界面', purpose: '通过同源 proxy2 读取模型列表，并在 RisuAI 中新建、切换、重命名、覆盖和删除自定义 API 配置档。', artifact: 'patches/risuai/scripts/patch-custom-model-profiles.mjs', prerequisite: '核对目标构建、proxy2 代理与现有模型输入框；API 配置仍留在 RisuAI。', verify: '刷新模型列表，新建、切换、重命名、确认覆盖和删除配置档，检查手动输入模型名仍可保存。', command: 'node patches/risuai/install.mjs --patch api-profiles --frontend <index.js>' },
  { id: 'image-router', name: '图像路由', kind: 'bundle', target: '已核对的 RisuAI 前端构建', purpose: '按请求内容在本机 ComfyUI 与既有网络图像接口间路由。', artifact: 'patches/risuai/scripts/patch-image-router.mjs', prerequisite: '需要 RisuAI 图像设置中两侧提供商均已配置；先核对脚本支持的目标构建。', verify: '分别用两类测试请求检查实际调用的提供商，确认文本模型路径未受影响。', command: 'node patches/risuai/install.mjs --patch image-router --frontend <database.js>' },
  { id: 'read-performance', name: '远程读取性能', kind: 'bundle', target: '已核对的前端与 server.cjs', purpose: '调整远程资源批量读取与并发处理。', artifact: 'patches/risuai/scripts/patch-read-batch.mjs + patch-read-batch-server.mjs', prerequisite: '前后端补丁需配套；保留程序和存档备份，并逐一确认构建锚点。', verify: '检查批量读取接口、资源加载及服务日志；浏览器完整加载需单独验证。', command: 'node patches/risuai/install.mjs --patch read-performance --frontend <database.js> --server <server.cjs>' },
  { id: 'read-cache', name: '远程资源本地缓存', kind: 'bundle', target: '已核对的 RisuAI 前端构建', purpose: '减少重复读取远程角色资源；与批量读取补丁作用于同一存储链路。', artifact: 'patches/risuai/scripts/patch-read-cache.mjs + patch-read-cache-evict.mjs', prerequisite: '先确认已有批量读取补丁的版本与应用顺序；不要把历史预生成的 JS 当作当前构建。', verify: '分别检查首次读取、重复读取和删除后的缓存失效。', command: 'node patches/risuai/install.mjs --patch read-cache --frontend <database.js>' },
  { id: 'list-cache', name: '资源清单缓存', kind: 'server', target: '已核对的前端与 server.cjs', purpose: '缓存远程资源清单并用修订信息减少重复传输。', artifact: 'patches/risuai/scripts/patch-list-local-cache.mjs + patch-list-etag-server.mjs', prerequisite: '前端和服务端配套应用；先备份并核对 /api/list 的当前响应语义。', verify: '检查首次获取、未变化返回、资源写入后的修订更新及重新加载后的完整列表。', command: 'node patches/risuai/install.mjs --patch list-cache --frontend <database.js> --server <server.cjs>' },
  { id: 'ingress-cache', name: '入口静态资源缓存', kind: 'server', target: 'RisuAI 入口代理与 dist 资源', purpose: '调整带内容哈希的静态资源缓存头与 source map 发布方式。', artifact: 'risuai-patches/2026-09-15-nginx-cache-and-sourcemaps.md', prerequisite: '这是部署记录，没有通用重放脚本；确认当前代理配置、资源命名和回滚副本。', verify: '用浏览器网络面板检查首次加载、重复加载的缓存头，以及资源更新后的新文件请求。' },
];
